# Generated by Django 4.2.5 on 2023-10-16 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Датчик')),
                ('description', models.CharField(default='Датчик без имени', max_length=100, null=True, verbose_name='Расположение')),
            ],
            options={
                'verbose_name': 'Датчик',
                'verbose_name_plural': 'Датчики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(max_length=4, verbose_name='Температура')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Время измерения')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='measurement.sensor', verbose_name='Датчик')),
            ],
            options={
                'verbose_name': 'Температура',
                'verbose_name_plural': 'Температуры',
                'ordering': ['sensor', 'created_at'],
            },
        ),
    ]
